import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class PaginationService {
  data = [
    { id: 1, title: 'Grease 2', genre: 'Comedy | Musical | Romance', language: 'Slovenian' },
    { id: 2, title: 'Captain Ron', genre: 'Adventure | Comedy', language: 'Northern Sami' },
    {
      id: 3,
      title: "We All Loved Each Other So Much (C'eravamo tanto amati)",
      genre: 'Comedy | Drama',
      language: 'Corsican',
    },
    { id: 4, title: 'Reader, The', genre: 'Drama | Romance', language: 'Latvian' },
    { id: 5, title: 'Illegal', genre: 'Drama', language: 'Kirghiz' },
    { id: 6, title: 'Children of a Lesser God', genre: 'Drama', language: 'Danish' },
    { id: 7, title: 'Wedding Singer, The', genre: 'Comedy | Romance', language: 'Georgian' },
    { id: 8, title: 'Lascars', genre: 'Animation | Comedy', language: 'Ossetian' },
    {
      id: 9,
      title: 'Pelle the Conqueror (Pelle erobreren)',
      genre: 'Drama',
      language: 'Estonian',
    },
    {
      id: 10,
      title: 'Machinist, The (Maquinista, El)',
      genre: 'Mystery | Thriller',
      language: 'Pali',
    },
    { id: 11, title: 'Envy', genre: 'Comedy', language: 'Breton' },
    {
      id: 12,
      title: 'Gozu (Gokudô kyôfu dai-gekijô: Gozu)',
      genre: 'Comedy | Crime | Drama | Horror | Mystery',
      language: 'German',
    },
    { id: 13, title: 'Reeker', genre: 'Horror | Mystery', language: 'Mongolian' },
    {
      id: 14,
      title: 'The Monkey King',
      genre: 'Action | Adventure | Children | IMAX',
      language: 'Aragonese',
    },
    { id: 15, title: 'Syrian Bride, The', genre: 'Drama', language: 'Volapük' },
    {
      id: 16,
      title: 'Prisoner of Zenda, The',
      genre: 'Action | Adventure | Romance',
      language: 'Malayalam',
    },
    {
      id: 17,
      title: 'Evenings on a Farm near Dikanka',
      genre: 'Comedy | Fantasy | Romance',
      language: 'Irish',
    },
    { id: 18, title: 'All About Eve', genre: 'Drama', language: 'Estonian' },
    {
      id: 19,
      title: 'Fantastic Four: Rise of the Silver Surfer',
      genre: 'Action | Adventure | Sci-Fi',
      language: 'Bislama',
    },
    { id: 20, title: 'Kazaam', genre: 'Children | Comedy | Fantasy', language: 'Western Frisian' },
    { id: 21, title: 'East is East', genre: 'Comedy', language: 'Yiddish' },
    {
      id: 22,
      title: "Man Who Loved Women, The (Homme qui aimait les femmes, L')",
      genre: 'Comedy | Drama | Romance',
      language: 'Ndonga',
    },
    { id: 23, title: 'Bringing Up Bobby', genre: 'Comedy', language: 'Vietnamese' },
    {
      id: 24,
      title: "Pan's Labyrinth (Laberinto del fauno, El)",
      genre: 'Drama | Fantasy | Thriller',
      language: 'Interlingue',
    },
    {
      id: 25,
      title: 'Invisible Ghost',
      genre: 'Action | Horror | Mystery | Thriller',
      language: 'Wolof',
    },
    { id: 26, title: 'Western', genre: 'Comedy | Romance', language: 'Ndebele, South' },
    {
      id: 27,
      title: "Beat That My Heart Skipped, The (battre mon coeur s'est arrêté, De)",
      genre: 'Drama',
      language: 'Tonga (Tonga Islands)',
    },
    {
      id: 28,
      title: 'Steamboat Willie',
      genre: 'Animation | Children | Comedy | Musical',
      language: 'Church Slavic',
    },
    {
      id: 29,
      title: 'Raiders of Atlantis, The',
      genre: 'Action | Mystery | Sci-Fi',
      language: 'Korean',
    },
    {
      id: 30,
      title: 'Stardust',
      genre: 'Adventure | Comedy | Fantasy | Romance',
      language: 'Kashmiri',
    },
    { id: 31, title: 'Free Money', genre: 'Comedy | Crime', language: 'Sindhi' },
    { id: 32, title: 'The Vexxer', genre: 'Comedy | Crime', language: 'Catalan' },
    {
      id: 33,
      title: 'Two Mules for Sister Sara',
      genre: 'Comedy | War | Western',
      language: 'Tamil',
    },
    { id: 34, title: 'Wild Angels, The', genre: 'Action | Drama', language: 'Russian' },
    { id: 35, title: 'Scum', genre: 'Crime | Drama', language: 'Ndebele, South' },
    {
      id: 36,
      title: 'Follow Me Quietly',
      genre: 'Crime | Drama | Film-Noir | Mystery',
      language: 'Hiri Motu',
    },
    { id: 37, title: 'Step Into Liquid', genre: 'Documentary', language: 'Italian' },
    { id: 38, title: 'Pulgasari', genre: 'Action | Drama | Fantasy', language: 'Armenian' },
    { id: 39, title: 'Iron Man: Rise Of Technovore', genre: 'Animation', language: 'Herero' },
    { id: 40, title: '13th Letter, The', genre: 'Film-Noir', language: 'Burmese' },
    { id: 41, title: 'Unknown', genre: 'Drama | Mystery | Thriller', language: 'Limburgan' },
    {
      id: 42,
      title: 'X2: X-Men United',
      genre: 'Action | Adventure | Sci-Fi | Thriller',
      language: 'Korean',
    },
    {
      id: 43,
      title: 'I Love, You Love (Ja milujem, ty milujes)',
      genre: 'Comedy | Drama | Romance',
      language: 'Macedonian',
    },
    { id: 44, title: 'Last Polka, The', genre: 'Comedy | Musical', language: 'Gaelic' },
    {
      id: 45,
      title: "Akira Kurosawa's Dreams (Dreams)",
      genre: 'Drama | Fantasy',
      language: 'Divehi',
    },
    { id: 46, title: 'Loser', genre: 'Comedy | Romance', language: 'Tibetan' },
    {
      id: 47,
      title: 'Look at Me (Comme une image)',
      genre: 'Comedy | Drama | Romance',
      language: 'Danish',
    },
    { id: 48, title: 'Oath, The', genre: 'Documentary', language: 'Pushto' },
    { id: 49, title: 'Mohabbatein', genre: 'Drama | Musical | Romance', language: 'Bislama' },
    { id: 50, title: 'Game 6', genre: 'Comedy | Drama', language: 'Basque' },
    { id: 51, title: 'Wind That Shakes the Barley, The', genre: 'Drama | War', language: 'Hebrew' },
    { id: 52, title: 'Puff, Puff, Pass', genre: 'Comedy', language: 'Romanian' },
    { id: 53, title: 'Buttcrack', genre: 'Comedy | Horror', language: 'Icelandic' },
    {
      id: 54,
      title: 'Blonde Crazy',
      genre: 'Comedy | Crime | Drama | Romance',
      language: 'Church Slavic',
    },
    { id: 55, title: 'Europa Report', genre: 'Sci-Fi | Thriller', language: 'Navajo' },
    { id: 56, title: 'Comme un chef', genre: 'Comedy', language: 'Oromo' },
    { id: 57, title: 'Kenny Begins', genre: 'Action | Comedy | Sci-Fi', language: 'Russian' },
    {
      id: 58,
      title: 'Varan the Unbelievable',
      genre: 'Action | Drama | Sci-Fi',
      language: 'Sango',
    },
    { id: 59, title: 'Blue Valentine', genre: 'Drama | Romance', language: 'Croatian' },
  ];

  getData() {
    return this.data;
  }
}
